#!/bin/bash
rm -rf d
if [ ! -z $1 ]; then
    current=$(pwd)
    path="${BASH_SOURCE%/*}/domains/$1"
    mkdir -p $path
    cd $path
    if [ ! -f key.pem ]; then
        openssl genrsa 4096 > key.pem && chmod 600 key.pem
    fi
    if [ ! -f csr.pem ]; then
        openssl req -new -sha256 -key key.pem -subj "/CN=$1" > csr.pem
    fi
    if [ ! -f renew ]; then
        cp ../../resources/domains/renew .
    fi
    if [ ! -f install-nginx ]; then
        cp ../../resources/domains/install-nginx .
    fi
    if [ ! -f install-nginx ]; then
        cp ../../resources/domains/install-cron .
    fi
    if [ ! -f domain.conf ]; then
        sed -e "s|\[domain\]|$1|g" -e "s|\[path\]|$(pwd)|g" ../../resources/domains/domain.conf > domain.conf
    fi
    cd $current
else 
    echo "Usage: add-domain domain"
fi
